// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BeerDeleteController from "./beer_delete_controller"
application.register("beer-delete", BeerDeleteController)

import BeerIconController from "./beer_icon_controller"
application.register("beer-icon", BeerIconController)

import ChatBroadcastController from "./chat_broadcast_controller"
application.register("chat-broadcast", ChatBroadcastController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MessageScrollController from "./message_scroll_controller"
application.register("message-scroll", MessageScrollController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)
